title:        io
tagline:      "saglac.io"
url:          http://andhyde.com
author:
  name:       ""
  email:      ""
markdown:     redcarpet
permalink:    pretty
highlighter:  rouge
paginate:     5
# plugins: [jekyll-paginate]
sass:
  sass_dir: _sass
