title:        io
tagline:      "saglac.io"
url:          http://andhyde.com
email:        info@saglac.io
author:
  name:       ""
  email:      ""
markdown:     redcarpet
permalink:    pretty
highlighter:  rouge
paginate:     5
# plugins: [jekyll-paginate]
sass:
  sass_dir: _sass

facebook_app_id: 130024877754864
facebook_default_image: /images/open-graph-default-image.png

