title:        Saglac IO
tagline:      "Rencontre technologique du Saguenay&mdash;Lac-St-Jean"
description:  "Le Saglac IO se veut un événement informel entre passionnés de technologies."
url:          http://saglac.io
email:        info@saglac.io
markdown:     redcarpet
permalink:    pretty
highlighter:  rouge
#paginate:     5
#plugins: [jekyll-paginate]
sass:
  sass_dir: _sass

facebook:
  app_id: 130024877754864
  default_image: /images/open-graph-default-image.png
  page: https://www.facebook.com/saglacio/
  group: https://www.facebook.com/groups/saglac.io/

twitter:
  handle: saglacio
  url: https://twitter.com/saglacio

mailing:
  url: https://saglac.us17.list-manage.com/subscribe/post?u=c9f3c71f1370a7e550caa409b&amp;id=f45e751233
